[system]
compatible=CrossControl V700
bootloader=uboot
data-directory=/data/rauc
bundle-formats=-plain
boot-attempts=5
boot-attempts-primary=5

[keyring]
directory=/data/rauc/certs/
check-purpose=codesign

[encryption]
key=pkcs11:token=rauc-token;id=%02;type=private
cert=pkcs11:token=rauc-token;id=%02;type=cert

[log.install-log]
filename=install.log
events=install
format=readable
max-size=100K
max-files=5

[slot.bootloader.0]
device=/dev/mmcblk1
type=boot-emmc
install-same=false

[slot.rootfs.0]
device=/dev/mmcblk1p2
type=ext4
bootname=A
install-same=false

[slot.rootfs.1]
device=/dev/mmcblk1p3
type=ext4
bootname=B
install-same=false

[slot.appfs.0]
device=/dev/mmcblk1p4
type=ext4
parent=rootfs.0
install-same=false

[slot.appfs.1]
device=/dev/mmcblk1p5
type=ext4
parent=rootfs.1
install-same=false

